{
 "title": "MySQL Replication Summary",
 "tags": [ "MySQL_HA" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mysql_up, replication_set)"
    }
   },
   {
    "name": "instance",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysql_up{replication_set=~\"$replication_set\"}, instance)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mysql_up{instance=~\"$instance\"}, node_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "query_result(mysql_version_info{instance=~\"$instance\"})"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "stat",
   "description": "Displays whether the IO Thread is in the running state or not. Applies only to a Replica host. The IO Thread connects to the Source host and reads binary log events, and then copies them locally to a file called the relay log.\n\nPossible values:\n\n**Yes** – IO Thread is running and is connected to a Source\n\n**No** – The IO Thread is not running because it is not yet started, or because an error occured while connecting to the Source\n\n**Connecting** – The IO Thread is running but is not fully connected to a Source\n\n**No value** – The host is not configured to be a Replica.\n\nIO Thread Running is one of the parameters returned by **SHOW SLAVE STATUS** command.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(min_over_time(mysql_slave_status_slave_io_running{instance=~\"$instance\"}[$interval]) or min_over_time(mysql_slave_status_slave_io_running{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "stat",
   "description": "Displays whether the SQL Thread is in the running state or not. Applies only to a Replica host. The SQL Thread reads the events from the local relay log file and applies them to the Replica host.  Depending on the format of the binary log it can read query statements (STATEMENT format) and re-executes them, or by reading row changes (ROW format) and applying only the changes.\n\nPossible values:\n\n**Yes** – The SQL Thread is running and is applying events from the relay log to the local Replica host\n\n**No** – The SQL Thread is not running because it is not yet started, or because of an error\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$instance\"}[$interval]) or min_over_time(mysql_slave_status_slave_sql_running{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "stat",
   "description": "Displays the number of the last error that the SQL Thread encountered which caused replication to stop.\n\nOne of the more common errors is \"Error: 1022 Duplicate Key Entry\". In such a case replication is attempting to update a row that already exists on the Replica. The SQL Thread will stop replication in order to avoid data corruption.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(max_over_time(mysql_slave_status_last_errno{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_slave_status_last_errno{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "stat",
   "description": "Displays whether the host is configured to be in Read Only mode or not.\n\nPossible values:\n\n**Yes** – the host blocks client updates except from users who have the SUPER or REPLICATION SLAVE privilege.This kind of configuration is typically used on Replica hosts in a replication environment to prevent client data modification causing inconsistencies and stopping the replication process.\n\n**No** – the host is not configured for Read Only mode, and will permit local client data modification operations (if the client has appropriate privileges to the database objects).",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(min_over_time(mysql_global_variables_read_only{instance=~\"$instance\"}[$interval]) or min_over_time(mysql_global_variables_read_only{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Replication Delay",
   "type": "stat",
   "description": "MySQL supports delayed replication such that a replica server deliberately executes transactions later than the source by at least a specified amount of time.\n\nThe default replication delay is 0 seconds. Use the CHANGE MASTER TO MASTER_DELAY=N statement to set the delay to N seconds. A transaction received from the source is not executed until at least N seconds later than its commit on the immediate source. \n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_slave_status_sql_delay{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_slave_status_sql_delay{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "MySQL Replication Lag",
   "type": "graph",
   "description": "Shows the number of seconds the Replica host is delayed in replication applying events compared to when the Source host applied them, denoted by the **Seconds_Behind_Source** value, and only applies to a Replica host. The most common reasons for Replicas to lag their Source are:\n\n* Network round trip time - High latency links will lead to non-zero replication lag values\n\n* Single threaded nature of replication channels - Source servers have the advantage of applying changes in parallel, whereas Replicas are only able to apply changes in serial, thus limiting their throughput.  In some cases Group Commit can help but is not always applicable.\n\n* High number of changed rows or computationally expensive SQL - Depending on the replication format (ROW vs STATEMENT), significant changes to the database through high volume of rows modified, or expensive CPU will all contribute to Replicas lagging behind their Source\n\nGenerally adding more CPU or Disk resources can alleviate replication lag issues, up to a point.\n\nSee also:",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp_min(avg by (instance) (\n(max_over_time(mysql_slave_status_seconds_behind_master{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_slave_status_seconds_behind_master{instance=~\"$instance\"}[5m])) - (max_over_time(mysql_slave_status_sql_delay{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_slave_status_sql_delay{instance=~\"$instance\"}[$interval]))\n),0)",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Binlogs Size",
   "type": "graph",
   "description": "Shows the overall size of the binary log files, which can exist on both Sources and Replicas. The binary log (also known as the binlog) contains events that describe database changes: CREATE TABLE, ALTER TABLE, updates, inserts, deletes and other statements or database changes. The binlog is the file that is read by Replicas via their IO Thread process in order to replicate database changes modification on the data and on the table structures. There can be more than one binlog file present depending on the binlog rotation policy adopted (for example using the configuration variables **max_binlog_size** and **expire_logs_days**).\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_binlog_size_bytes{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_binlog_size_bytes{instance=~\"$instance\"}[5m])) or avg by (node_name) (max_over_time(aws_rds_bin_log_disk_usage_average{node_name=~\"$node_name\"}[$interval]) or max_over_time(aws_rds_bin_log_disk_usage_average{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlog Data Written Hourly",
   "type": "graph",
   "description": "Shows the amount of data written to the binlog files, grouped into hourly buckets. This graph can give you an idea of the amount of changes to your data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (increase(mysql_binlog_size_bytes{instance=~\"$instance\"}[1h])) or \navg by (node_name) (increase(aws_rds_bin_log_disk_usage_average{node_name=~\"$node_name\"}[1h]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlogs Count",
   "type": "graph",
   "description": "Shows the overall count of binary log files, which can exist on both Sources and Replicas. The binary log (also known as the binlog) contains events that describe database changes: CREATE TABLE, ALTER TABLE, updates, inserts, deletes and other statements or database changes. The binlog is the file that is read by Replicas via their IO Thread process in order to replicate database changes modification on the data and on the table structures. There can be more than one binlog file present depending on the binlog rotation policy adopted (for example using the configuration variables **max_binlog_size** and **expire_logs_days**).\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_binlog_files{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_binlog_files{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Binlogs Created Hourly",
   "type": "graph",
   "description": "Shows the number of binlog files created hourly. The number depends on the rotation policy adopted using the configuration variables **max_binlog_size** and **expire_logs_days**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (increase(mysql_binlog_file_number{instance=~\"$instance\"}[1h]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Relay Log Space",
   "type": "graph",
   "description": "Shows the overall size of the relay log files, and applies only to Replicas. The relay log consists of a set of numbered files containing the events to be executed on a Replica in order to replicate database changes.  As soon as the SQL Thread completes execution of all events in a relay log file, the relay log file is then deleted by MySQL.\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_slave_status_relay_log_space{instance=~\"$instance\"}[$interval]) or max_over_time(mysql_slave_status_relay_log_space{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Relay Log Written Hourly",
   "type": "graph",
   "description": "Shows the amount of data written hourly to the relay log files.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (increase(mysql_slave_status_relay_log_space{instance=~\"$instance\"}[1h]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "MySQL Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mysql_global_status_uptime{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "options": {
    "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
   }
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (rate(mysql_global_status_queries{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "File Handlers Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(max_over_time(mysql_global_status_open_files{instance=~\"$instance\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{instance=~\"$instance\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{instance=~\"$instance\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{instance=~\"$instance\"}[5m]))\r)"
    }
   ]
  },
  {
   "title": "Table Open Cache Miss Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (1-((rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[5m])))))"
    }
   ]
  },
  {
   "title": "Table Open Cache Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mysql_global_variables_table_open_cache{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Table Definition Cache Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (instance) (mysql_global_variables_table_definition_cache{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 36 },
   "options": {
    "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-service_name=$service_name\" target=\"_blank\">$service_name</h5>"
   }
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max(max_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[5m])))",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_max_used_connections{instance=~\"$instance\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_variables_max_connections{instance=~\"$instance\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (max_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg by (instance) (avg_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,handler) (rate(mysql_global_status_handlers_total{instance=~\"$instance\"}[$interval]) or \nirate(mysql_global_status_handlers_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(10, avg by (instance,command) (rate(mysql_global_status_commands_total{instance=~\"$instance\"}[$interval]))>0) or \navg by (instance) (irate(mysql_global_status_commands_total{instance=~\"$instance\"}[5m]))>0",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance,state) (max_over_time(mysql_info_schema_threads{instance=~\"$instance\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(mysql_global_status_bytes_received{instance=~\"$instance\"}[$interval]) or \nirate(mysql_global_status_bytes_received{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (instance) (rate(mysql_global_status_bytes_sent{instance=~\"$instance\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}